apiVersion: v1
kind: ConfigMap
metadata:
  name: bwki-webhook-configmap
  namespace: bwki
data:
  sidecarconfig.yaml: |
    initContainers:
    - name: populate
      image: bitfusiondeviceplugin/bitfusion-client:test
      command: [/bin/bash, -c, "
            cp -a /bitfusion /bitfusion-distro
            "]
      volumeMounts:
      - name: bitfusion
        mountPath: /bitfusion-distro
      - name: client-dir
        mountPath: /client
      - name: client
        mountPath: /root/.bitfusion/client.yaml
        subPath: client.yaml
    containers:
    - name: sidecar-container
      image: container
      env:
      - name: LD_LIBRARY_PATH
        value: ""
      volumeMounts:
      - name: bitfusion
        mountPath: /bitfusion
      - name: ca
        mountPath: /etc/bitfusion
      - name: client-dir
        mountPath: /root/.bitfusion/client.yaml
        subPath: client.yaml
      - name: servers
        mountPath: /root/.bitfusion/servers.conf
        subPath: servers.conf
    volumes:
    - name: bitfusion
      emptyDir: {}
    - name: client-dir
      emptyDir: {}
    - name: ca
      secret:
        secretName: bitfusion-secret
        items:
          - key: ca.crt
            path: tls/ca.crt
    - name: client
      secret:
        secretName: bitfusion-secret
        items:
          - key: client.yaml
            path: client.yaml
            mode: 0600
    - name: servers
      secret:
        secretName: bitfusion-secret
        items:
          - key: servers.conf
            path: servers.conf
