apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "validation.bitfusion.io-cfg"
  labels:
    app: sidecar-injector
webhooks:
  - name:  "sidecar-injector.bitfusion.io"
    clientConfig:
      service:
        name: "sidecar-injector-webhook-svc"
        namespace: "sidecar-injector"
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    admissionReviewVersions: [ "v1", "v1beta1" ]
    sideEffects: None
    timeoutSeconds: 5
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
